// "Talk to an advisor" enquiries for the Aug 2026 preview.
//
// Kyle's note: custom dates come out, replaced by an advisor option where you
// leave a WhatsApp number or an email only — "this then sends to the same
// database". Rows land in public.advisor_enquiries alongside the bookings.
//
// The table is anon insert-only: no select policy, so a leaked publishable key
// can drop an enquiry in but cannot read anybody else's back out.
import type { SupabaseClient } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";

// src/integrations/supabase/types.ts is generated by Lovable and doesn't know
// about advisor_enquiries yet, so this one call is cast rather than hand-editing
// a file that gets regenerated.
const db = supabase as unknown as SupabaseClient;

export type ContactMethod = "whatsapp" | "email";

export interface AdvisorEnquiry {
  tripSlug: string;
  tripName: string;
  method: ContactMethod;
  /** The number or address, as typed. */
  value: string;
}

/** Loose on purpose — an advisor is going to read these, not a mail server. */
export function validateContact(method: ContactMethod, value: string): string | null {
  const v = value.trim();
  if (!v) return method === "whatsapp" ? "Add your WhatsApp number" : "Add your email";
  if (method === "email") return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(v) ? null : "That email doesn't look right";
  return /^\+?[\d\s()-]{7,}$/.test(v) ? null : "That number doesn't look right";
}

export async function submitAdvisorEnquiry(input: AdvisorEnquiry): Promise<void> {
  const { error } = await db.from("advisor_enquiries").insert({
    trip_slug: input.tripSlug,
    trip_name: input.tripName,
    contact_method: input.method,
    contact_value: input.value.trim(),
    source: "preview",
  });
  if (error) throw new Error(error.message || "Could not send that just now");
}
